HW.4 Kube-networks
otus-kuber-2020-04/Tennki_platform pull request #5
Opened 2020-05-24 11:03 UTC by Tennki

# Выполнено ДЗ № 4

 - [X] Основное ДЗ
 - [X] Задание со *

## В процессе сделано:
- В под web добавлены проверки работоспособности.
- Создан Deployment для запуска web приложения.
- Создан сервис ClusterIP (kubernetes-networks/web-svc-cip.yaml)
- Включен IPVS в minikube
- Развернут MetalLB
- Создан сервис LoadBalancer для приложения
- Создан сервис LoadBalancer для публикации CoreDNS наружу.
- Развернут Ingress Nginx
- Развернут Kubernetes Dashboard
- Dashboars опубликован через Ingress
- Проверен Сanary releaseчерез ingress-nginx
  - Модифицирован прод Ingress
  - Создан Namespace Canary
  - Развернут Canary deployment
  - Создан сервис LoadBalancer для Canary deployment
  - Создан Canary Ingress

## Как запустить проект:
 - kubectl apply -f kubernetes-networks/web-deploy.yaml
 - kubectl apply -f kubernetes-networks/web-svc-lb.yaml
 - kubectl apply -f kubernetes-networks/web-svc-headless.yaml
 - kubectl apply -f kubernetes-networks/web-ingress.yaml
 - kubectl apply -f kubernetes-networks/coredns/coredns-svc-lb.yaml
 - kubectl apply -f kubernetes-networks/dashboard/dashboard-ingress.yaml
 - kubectl apply -f kubernetes-networks/canary/

## Как проверить работоспособность:
 - nslookup web-svc-cip.default.svc.cluster.local <loadbalancer_ip>
 - Перейти по ссылке http://<loadbalancer_ip>/web
 - Перейти по ссылке http://<loadbalancer_ip>/dashboard
 - curl -s -H "canary: always" --resolve web.local:80:<loadbalancer_ip> web.local/web

## PR checklist:
 - [X] Выставлен label с темой домашнего задания

2020-05-24 19:00 UTC, Jasstkn requested changes
Добрый день.
Основное задание выполнено верно, как и задания с coredns, и kubernetes-dashboard. Ваш вариант кенери у меня не заработал. Предлагаю упростить немного вашу конфигурацию:
в namespace canary задеплоите 2 деплоймента - один для кенери, другой основной, также каждому по сервису и ингрессу, на кенери ингрессе выставите ваши аннотации и попробуйте проверить - можно даже не использовать host

2020-05-24 19:00 UTC, Jasstkn commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
У сервиса canary-svc нет порта 8000, только 80. Плюс переделайте пожалуйста вашу конфигурацию на один немспейс - у меня ваш вариант не заработал и отдает 503.

2020-05-25 11:15 UTC, Tennki commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
Добрый день!
Переделал canary. По итогу балансировка так и не заработала без host. У меня тоже была 503, из-за ингресса в default namespace c такими же параметрами как в canary.

2020-05-26 06:38 UTC, Jasstkn commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
потому что host указан, если его не указывать - будет подставлена звездочка =)

2020-05-26 06:55 UTC, Tennki commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
Я пробовал, без host, убирал из prod и canary ingress. У меня весь трафик попадал на "прод" не зависимо от хэдера. Непонятно.%)

2020-05-26 07:11 UTC, Jasstkn commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
Задебажу тогда сейчас =)

2020-05-26 08:01 UTC, Jasstkn commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
Получилось завести.

2020-05-26 08:09 UTC, Jasstkn commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
<img width="1043" alt="Screenshot 2020-05-26 at 11 08 45" src="https://user-images.githubusercontent.com/20466436/82876328-4656b680-9f41-11ea-89e9-1c80c244a6c2.png">

задеплоила все в один немспейс canary и убрала .local из хостнейма

2020-05-26 08:32 UTC, Tennki commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
Так все равно получается директива host остается.) Если ее вообще убрать ингрес начинает ругаться и весь трафик летит в прод.
![Снимок экрана 2020-05-26 в 11 28 15](https://user-images.githubusercontent.com/41969752/82878711-84a1a500-9f44-11ea-8d26-a65b5674d1d6.png)

2020-05-28 06:42 UTC, Jasstkn commented on kubernetes-networks/canary/04-canary-ingress.yaml
> +          servicePort: 8000
ага, да, с кенери без хоста не обойтись. домашку принимаю - с кенери-то мы в итоге разобрались и все работает.

2020-05-28 06:43 UTC, Jasstkn approved these changes

2020-05-28 06:43 UTC, merged